package ui

import (
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"

	tea "github.com/charmbracelet/bubbletea"
	uv "github.com/charmbracelet/ultraviolet"
	"github.com/charmbracelet/x/vt"
	"github.com/creack/pty"
)

type terminalSession struct {
	pty        *os.File
	command    *exec.Cmd
	emulator   *vt.SafeEmulator
	cwd        string
	shell      string
	exited     bool
	bridgeDone chan struct{}
	closeOnce  sync.Once
}

type terminalOutputMsg struct {
	session *terminalSession
	data    []byte
	err     error
}

type terminalExitedMsg struct {
	session *terminalSession
	err     error
}

func startTerminalSession(cwd string, width, height int) (*terminalSession, error) {
	shell := os.Getenv("SHELL")
	if shell == "" {
		shell = "/bin/sh"
	}
	command := exec.Command(shell)
	command.Dir = cwd
	command.Env = terminalEnvironment(os.Environ())
	emulator := vt.NewSafeEmulator(max(1, width), max(1, height))
	ptyFile, err := pty.StartWithSize(command, terminalWindowSize(width, height))
	if err != nil {
		_ = emulator.Close()
		return nil, err
	}
	session := &terminalSession{
		pty: ptyFile, command: command, emulator: emulator, cwd: cwd, shell: filepath.Base(shell),
		bridgeDone: make(chan struct{}),
	}
	// The emulator encodes keys according to the shell's active terminal modes
	// and answers terminal queries generated by interactive programs.
	go func() {
		defer close(session.bridgeDone)
		_, _ = io.Copy(ptyFile, emulator)
	}()
	return session, nil
}

func terminalEnvironment(environment []string) []string {
	result := make([]string, 0, len(environment)+2)
	for _, entry := range environment {
		if strings.HasPrefix(entry, "TERM=") || strings.HasPrefix(entry, "COLORTERM=") {
			continue
		}
		result = append(result, entry)
	}
	return append(result, "TERM=xterm-256color", "COLORTERM=truecolor")
}

func terminalWindowSize(width, height int) *pty.Winsize {
	return &pty.Winsize{Cols: uint16(max(1, min(width, 65535))), Rows: uint16(max(1, min(height, 65535)))}
}

func (s *terminalSession) resize(width, height int) error {
	width, height = max(1, width), max(1, height)
	if s.emulator.Width() == width && s.emulator.Height() == height {
		return nil
	}
	if err := pty.Setsize(s.pty, terminalWindowSize(width, height)); err != nil {
		return err
	}
	s.emulator.Resize(width, height)
	return nil
}

func (s *terminalSession) close() {
	if s == nil {
		return
	}
	s.closeOnce.Do(func() {
		// Close the emulator's input pipe first so the PTY bridge stops reading.
		// SafeEmulator.Close does not serialize its closed flag with Read, so it
		// must only run after the bridge has exited.
		if input, ok := s.emulator.InputPipe().(io.Closer); ok {
			_ = input.Close()
		}
		_ = s.pty.Close()
		if s.command.Process != nil {
			_ = s.command.Process.Kill()
		}
		<-s.bridgeDone
		_ = s.emulator.Close()
	})
}

func readTerminalCmd(session *terminalSession) tea.Cmd {
	return func() tea.Msg {
		buffer := make([]byte, 32*1024)
		count, err := session.pty.Read(buffer)
		return terminalOutputMsg{session: session, data: append([]byte(nil), buffer[:count]...), err: err}
	}
}

func waitTerminalCmd(session *terminalSession) tea.Cmd {
	return func() tea.Msg {
		return terminalExitedMsg{session: session, err: session.command.Wait()}
	}
}

func (m *Model) toggleTerminal() tea.Cmd {
	if m.terminalVisible {
		m.terminalVisible = false
		for _, pane := range m.panes {
			pane.clamp(m.visibleRows())
		}
		m.setStatus("Terminal hidden", false)
		return nil
	}
	m.terminalVisible = true
	if m.terminal == nil || m.terminal.exited {
		if m.terminal != nil {
			m.terminal.close()
		}
		cwd := m.terminalWorkingDirectory()
		width, height := m.terminalViewportSize()
		session, err := startTerminalSession(cwd, width, height)
		if err != nil {
			m.terminalVisible = false
			m.setStatus("Open terminal: "+err.Error(), true)
			return nil
		}
		m.terminal = session
		m.setStatus("Terminal opened in "+cwd, false)
		for _, pane := range m.panes {
			pane.clamp(m.visibleRows())
		}
		return tea.Batch(readTerminalCmd(session), waitTerminalCmd(session))
	}
	if err := m.resizeTerminal(); err != nil {
		m.setStatus("Resize terminal: "+err.Error(), true)
	} else {
		m.setStatus("Terminal focused · F9 returns to files", false)
	}
	for _, pane := range m.panes {
		pane.clamp(m.visibleRows())
	}
	return nil
}

func (m *Model) terminalWorkingDirectory() string {
	for _, index := range []int{m.focus, 1 - m.focus} {
		pane := m.panes[index]
		if pane != nil && pane.location.Backend.ID() == "local" {
			return pane.location.Path
		}
	}
	directory, err := os.Getwd()
	if err != nil {
		return "/"
	}
	return directory
}

func (m *Model) terminalPanelHeight() int {
	if !m.terminalVisible {
		return 0
	}
	footerHeight := 1 + len(shortcutRows(max(1, m.width-2)))
	bodyHeight := max(1, m.height-3-footerHeight)
	desired := max(7, bodyHeight*2/5)
	return min(desired, max(2, bodyHeight-4))
}

func (m *Model) terminalViewportSize() (int, int) {
	return max(1, m.width-2), max(1, m.terminalPanelHeight()-1)
}

func (m *Model) resizeTerminal() error {
	if !m.terminalVisible || m.terminal == nil || m.terminal.exited {
		return nil
	}
	width, height := m.terminalViewportSize()
	return m.terminal.resize(width, height)
}

func (m *Model) sendTerminalKey(key tea.KeyMsg) {
	if m.terminal == nil || m.terminal.exited {
		return
	}
	emulator := m.terminal.emulator
	if key.Paste {
		emulator.Paste(string(key.Runes))
		return
	}
	if (key.Type >= tea.KeyNull && key.Type <= tea.KeyCtrlUnderscore) || key.Type == tea.KeyBackspace {
		text := string(rune(key.Type))
		if key.Alt {
			text = "\x1b" + text
		}
		emulator.SendText(text)
		return
	}
	if sequence := modifiedTerminalSequence(key.Type); sequence != "" {
		if key.Alt {
			sequence = "\x1b" + sequence
		}
		emulator.SendText(sequence)
		return
	}
	var code rune
	switch key.Type {
	case tea.KeyRunes:
		if len(key.Runes) != 1 {
			text := string(key.Runes)
			if key.Alt {
				text = "\x1b" + text
			}
			emulator.SendText(text)
			return
		}
		code = key.Runes[0]
	case tea.KeyUp:
		code = vt.KeyUp
	case tea.KeyDown:
		code = vt.KeyDown
	case tea.KeyRight:
		code = vt.KeyRight
	case tea.KeyLeft:
		code = vt.KeyLeft
	case tea.KeyShiftTab:
		code = vt.KeyTab
	case tea.KeyHome:
		code = vt.KeyHome
	case tea.KeyEnd:
		code = vt.KeyEnd
	case tea.KeyPgUp:
		code = vt.KeyPgUp
	case tea.KeyPgDown:
		code = vt.KeyPgDown
	case tea.KeyDelete:
		code = vt.KeyDelete
	case tea.KeyInsert:
		code = vt.KeyInsert
	case tea.KeySpace:
		code = ' '
	default:
		if key.Type >= tea.KeyF1 && key.Type <= tea.KeyF20 {
			code = vt.KeyF1 + rune(key.Type-tea.KeyF1)
		}
	}
	if code == 0 {
		return
	}
	modifiers := vt.KeyMod(0)
	if key.Alt {
		modifiers |= vt.ModAlt
	}
	if key.Type == tea.KeyShiftTab {
		modifiers |= vt.ModShift
	}
	emulator.SendKey(vt.KeyPressEvent{Code: code, Text: string(key.Runes), Mod: modifiers})
}

func modifiedTerminalSequence(keyType tea.KeyType) string {
	switch keyType {
	case tea.KeyCtrlUp:
		return "\x1b[1;5A"
	case tea.KeyCtrlDown:
		return "\x1b[1;5B"
	case tea.KeyCtrlRight:
		return "\x1b[1;5C"
	case tea.KeyCtrlLeft:
		return "\x1b[1;5D"
	case tea.KeyShiftUp:
		return "\x1b[1;2A"
	case tea.KeyShiftDown:
		return "\x1b[1;2B"
	case tea.KeyShiftRight:
		return "\x1b[1;2C"
	case tea.KeyShiftLeft:
		return "\x1b[1;2D"
	case tea.KeyCtrlShiftUp:
		return "\x1b[1;6A"
	case tea.KeyCtrlShiftDown:
		return "\x1b[1;6B"
	case tea.KeyCtrlShiftRight:
		return "\x1b[1;6C"
	case tea.KeyCtrlShiftLeft:
		return "\x1b[1;6D"
	case tea.KeyCtrlHome:
		return "\x1b[1;5H"
	case tea.KeyCtrlEnd:
		return "\x1b[1;5F"
	case tea.KeyShiftHome:
		return "\x1b[1;2H"
	case tea.KeyShiftEnd:
		return "\x1b[1;2F"
	case tea.KeyCtrlShiftHome:
		return "\x1b[1;6H"
	case tea.KeyCtrlShiftEnd:
		return "\x1b[1;6F"
	case tea.KeyCtrlPgUp:
		return "\x1b[5;5~"
	case tea.KeyCtrlPgDown:
		return "\x1b[6;5~"
	}
	return ""
}

func renderTerminalScreen(session *terminalSession) string {
	if session == nil || session.emulator == nil {
		return ""
	}
	position := session.emulator.CursorPosition()
	cell := session.emulator.CellAt(position.X, position.Y)
	if cell == nil {
		return session.emulator.Render()
	}
	original := cell.Clone()
	cursor := cell.Clone()
	if cursor.Content == "" {
		cursor.Content, cursor.Width = " ", 1
	}
	cursor.Style.Attrs ^= uv.AttrReverse
	session.emulator.SetCell(position.X, position.Y, cursor)
	rendered := session.emulator.Render()
	session.emulator.SetCell(position.X, position.Y, original)
	return rendered
}
